name: Build and Push Docker image

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/jbr:${{ matrix.tag }}
          build-args:
            JBRVERSION: 17.0.14
            JBRBUILD: 1367.22
            HOTSWAPAGENT: ${{ matrix.hotswap }}
        strategy:
          matrix:
            include:
              - tag: 17
                hotswap: false
              - tag: 17-ha
                hotswap: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.tags }}
          build-args:
            HOTSWAPAGENT: ${{ matrix.hotswap }}
        strategy:
          matrix:
            include:
              - tags: ${{ secrets.DOCKER_USERNAME }}/jbr:21
                hotswap: false
              - tags: |
                  ${{ secrets.DOCKER_USERNAME }}/jbr:21-ha
                  ${{ secrets.DOCKER_USERNAME }}/jbr:latest
                hotswap: true
